const fs = require('fs');

const htmlReplacements = {
    'Quản lý tài nguyên': 'Resource Management',
    'Tài khoản Facebook': 'Facebook Account',
    'Tài khoản quảng cáo': 'Ads Account',
    'Quản lý bài viết': 'Post Management',
    'Tạo bài viết': 'Create Post',
    'Quản lý quảng cáo Facebook': 'Facebook Ads Management',
    'Tạo quảng cáo': 'Create Ad',
    'Danh sách quảng cáo': 'Ads List',
    'Cài đặt': 'Settings',
    'Chính sách': 'Policies',
    'Dữ liệu cá nhân': 'Personal Data',
    'Đã xác thực': 'Authenticated',
    'Quản lý bài viết Facebook Fanpage': 'Facebook Fanpage Post Management',
    'Liên kết tài khoản cá nhân và tích hợp các kênh Fanpage để đồng bộ tuyển dụng': 'Link your personal account and integrate Fanpage channels to sync recruitment',
    'Liên kết tài khoản Facebook Business': 'Link Facebook Business Account',
    'Tích hợp tài khoản Facebook giúp bạn quản lý bài viết tuyển dụng trực tiếp và chat Messenger chăm sóc ứng viên thời gian thực trên Ezi Talent.': 'Integrating Facebook accounts helps you manage recruitment posts directly and chat on Messenger to support candidates in real-time on Ezi Talent.',
    'Kết nối tài khoản Facebook': 'Connect Facebook Account',
    'Trạng thái: Đã liên kết tài khoản Facebook': 'Status: Facebook Account Linked',
    'Hủy kết nối': 'Disconnect',
    'Các trang Fanpage đang đồng bộ dữ liệu:': 'Fanpages currently syncing data:',
    'Quyền hạn: Admin': 'Role: Admin',
    'Hoạt động': 'Active',
    '+ Thêm Fanpage liên kết': '+ Add Linked Fanpage',
    'Kết nối tài khoản quảng cáo để quản lý chiến dịch, ngân sách và theo dõi hiệu quả tuyển dụng.': 'Connect ads accounts to manage campaigns, budgets, and track recruitment performance.',
    'Liên kết tài khoản Quảng cáo': 'Link Ads Account',
    'Kết nối tài khoản quảng cáo để quản lý chiến dịch, ngân sách và theo dõi hiệu quả tuyển dụng trực tiếp.': 'Connect ads accounts to manage campaigns, budgets, and track recruitment performance directly.',
    'Kết nối tài khoản quảng cáo': 'Connect Ads Account',
    '+ Kết nối tài khoản quảng cáo': '+ Connect Ads Account',
    'Các tài khoản đã kết nối:': 'Connected accounts:',
    'Chưa có tài khoản nào': 'No accounts yet',
    'Vui lòng kết nối tài khoản quảng cáo để thiết lập chiến dịch.': 'Please connect an ads account to set up campaigns.',
    'Bài viết Facebook': 'Facebook Posts',
    'Tạo, chỉnh sửa và quản lý bài viết trên Fanpage': 'Create, edit, and manage Fanpage posts',
    'Tìm kiếm bài viết...': 'Search posts...',
    'Tất cả Fanpage': 'All Fanpages',
    'Chưa có bài viết nào': 'No posts yet',
    'Bấm "Tạo bài viết" để bắt đầu': 'Click "Create Post" to get started',
    'Tạo bài viết ngay': 'Create Post Now',
    'Tạo bài viết mới': 'Create New Post',
    'Soạn thảo bài viết và đăng lên Fanpage Facebook': 'Draft a post and publish it to Facebook Fanpage',
    'Fanpage đăng': 'Post to Fanpage',
    'Nội dung bài viết': 'Post Content',
    'Hình ảnh / Video minh họa': 'Illustrative Image / Video',
    'Tải lên hình ảnh hoặc video từ máy tính': 'Upload image or video from computer',
    'Hỗ trợ các định dạng ảnh và video (PNG, JPG, MP4)': 'Supports image and video formats (PNG, JPG, MP4)',
    'Hủy': 'Cancel',
    'Gỡ bỏ': 'Remove',
    'Bản xem trước': 'Preview',
    'Vừa xong': 'Just now',
    'Nội dung chi tiết bài viết sẽ được cập nhật trực tiếp tại đây khi bạn nhập vào biểu mẫu bên trái...': 'The detailed content of the post will be updated directly here as you enter the form on the left...',
    'Thích': 'Like',
    'Bình luận': 'Comment',
    'Chia sẻ': 'Share',
    'Nhập bình luận...': 'Write a comment...',
    'Inbox tuyển dụng Facebook Messenger': 'Facebook Messenger Recruitment Inbox',
    'Tương tác và hỗ trợ ứng viên': 'Interact and support candidates',
    'Tìm kiếm tin nhắn...': 'Search messages...',
    'Đang hoạt động': 'Active now',
    'Ngoại tuyến': 'Offline',
    'Tùy chọn': 'Options',
    'Nhập tin nhắn...': 'Type a message...',
    'Tạo chiến dịch quảng cáo': 'Create Ad Campaign',
    'Thiết lập mục tiêu, đối tượng và ngân sách chạy quảng cáo': 'Set goals, audience, and budget for ad campaign',
    'Mục tiêu chiến dịch': 'Campaign Objective',
    'Tên chiến dịch': 'Campaign Name',
    'Ngân sách (VNĐ)': 'Budget (VND)',
    'Ngày bắt đầu': 'Start Date',
    'Ngày kết thúc': 'End Date',
    'Tiếp tục': 'Continue',
    'Cài đặt nhóm quảng cáo': 'Ad Set Setup',
    'Tạo nội dung quảng cáo': 'Create Ad Content',
    'Danh sách chiến dịch quảng cáo Facebook': 'Facebook Ad Campaigns List',
    'Theo dõi và quản lý hiệu quả các chiến dịch': 'Track and manage campaign performance',
    'Chính sách hệ thống': 'System Policies',
    'Dữ liệu cá nhân của bạn': 'Your Personal Data',
    'Tải xuống bản sao dữ liệu': 'Download Data Copy',
    'Yêu cầu xóa dữ liệu': 'Request Data Deletion',
    'Tìm kiếm chiến dịch...': 'Search campaigns...',
    'Tất cả trạng thái': 'All statuses',
    'Đang chạy': 'Running',
    'Đã tạm dừng': 'Paused',
    'Đã hoàn thành': 'Completed',
    'Lưu nháp': 'Save Draft',
    'bình luận': 'comments',
    'lượt chia sẻ': 'shares',
    'Quản lý bình luận': 'Manage comments',
    'Chỉnh sửa': 'Edit',
    'Xóa': 'Delete',
    'Tương tác': 'Engagement',
    'Cập nhật bài viết': 'Update Post',
    'Chỉnh sửa bài viết': 'Edit Post',
    'Cập nhật lại nội dung bài đăng trên Fanpage': 'Update the content of the post on Fanpage',
    'Tạo quảng cáo Facebook': 'Create Facebook Ad',
    'Chỉnh sửa quảng cáo Facebook': 'Edit Facebook Ad'
};

function processFile(filePath) {
    let content = fs.readFileSync(filePath, 'utf8');
    for (const [vn, en] of Object.entries(htmlReplacements)) {
        content = content.split(vn).join(en);
    }
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`Processed ${filePath}`);
}

processFile('index.html');
processFile('app.js');
